//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspose.DNN.GmailSync.Data
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Aspose_GmailSync_ServerDetails
    {
        public int ID { get; set; }
        public int DNNUserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ClientID { get; set; }
        public string ClientSecret { get; set; }
        public string RefreshToken { get; set; }
    }
}
