//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ExchangeEntities : DbContext
{
    public ExchangeEntities()
        : base("name=ExchangeEntities")
    {
    }

    public ExchangeEntities(String nameOrConnectionString)
        : base(nameOrConnectionString)
    {
    }

    //public ExchangeEntities(String nameOrConnectionString)
    //    : base(nameOrConnectionString)
    //{
    //}

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Aspose_ExchangeSync_ServerDetails> Aspose_ExchangeSync_ServerDetails { get; set; }
}
